"use client";

import { useRouter } from "next/navigation";
import { FormEvent, useEffect, useState } from "react";

import { agentsApi, campaignsApi, tasksApi, type AgentListItem, type CampaignListItem, type TaskListItem, type TaskPriority, type TaskType } from "@/lib/api";
import { TASK_PRIORITIES, TASK_PRIORITY_LABELS, TASK_TYPES, TASK_TYPE_LABELS } from "@/lib/tasks";

export default function NewTaskPage() {
  const router = useRouter(); const [campaigns, setCampaigns] = useState<CampaignListItem[]>([]); const [agents, setAgents] = useState<AgentListItem[]>([]); const [available, setAvailable] = useState<TaskListItem[]>([]); const [campaignId, setCampaignId] = useState(""); const [title, setTitle] = useState(""); const [description, setDescription] = useState(""); const [taskType, setTaskType] = useState<TaskType>("MANUAL"); const [agentId, setAgentId] = useState(""); const [priority, setPriority] = useState<TaskPriority>("NORMAL"); const [deadline, setDeadline] = useState(""); const [requiresApproval, setRequiresApproval] = useState(false); const [dependencyIds, setDependencyIds] = useState<string[]>([]); const [input, setInput] = useState("{}"); const [error, setError] = useState("");
  useEffect(() => { Promise.all([campaignsApi.list(), agentsApi.list()]).then(([campaignRows, agentRows]) => { setCampaigns(campaignRows); setAgents(agentRows); const preset = new URLSearchParams(window.location.search).get("campaign_id") ?? ""; setCampaignId(preset); }); }, []);
  useEffect(() => { if (campaignId) tasksApi.list({ campaign_id: campaignId }).then(setAvailable); }, [campaignId]);
  async function submit(event: FormEvent) { event.preventDefault(); setError(""); if (!campaignId || !title.trim()) { setError("Кампания и название обязательны."); return; } let inputData: Record<string, unknown>; try { inputData = JSON.parse(input) as Record<string, unknown>; } catch { setError("Input Data должен содержать корректный JSON."); return; } try { const task = await tasksApi.create({ campaign_id: campaignId, title, description: description || null, task_type: taskType, assigned_agent_id: agentId || null, priority, deadline: deadline ? new Date(deadline).toISOString() : null, requires_approval: requiresApproval, input_data: inputData, dependency_ids: dependencyIds }); router.push(`/tasks/${task.id}`); } catch (reason) { setError(reason instanceof Error ? reason.message : "Не удалось создать задачу."); } }
  return <main><section><h1>Новая задача</h1><form onSubmit={submit}>{error && <p role="alert" className="error">{error}</p>}<label>Кампания *<select value={campaignId} onChange={(e) => setCampaignId(e.target.value)}><option value="">Выберите кампанию</option>{campaigns.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>Название *<input value={title} onChange={(e) => setTitle(e.target.value)} /></label><label>Описание<textarea value={description} onChange={(e) => setDescription(e.target.value)} /></label><label>Тип<select value={taskType} onChange={(e) => setTaskType(e.target.value as TaskType)}>{TASK_TYPES.map((item) => <option key={item} value={item}>{TASK_TYPE_LABELS[item]}</option>)}</select></label><label>Агент<select value={agentId} onChange={(e) => setAgentId(e.target.value)}><option value="">Не назначен</option>{agents.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>Приоритет<select value={priority} onChange={(e) => setPriority(e.target.value as TaskPriority)}>{TASK_PRIORITIES.map((item) => <option key={item} value={item}>{TASK_PRIORITY_LABELS[item]}</option>)}</select></label><label>Deadline<input type="datetime-local" value={deadline} onChange={(e) => setDeadline(e.target.value)} /></label><label>Зависит от<select multiple aria-label="Зависит от" value={dependencyIds} onChange={(e) => setDependencyIds(Array.from(e.target.selectedOptions, (option) => option.value))}>{available.map((item) => <option key={item.id} value={item.id}>{item.title}</option>)}</select></label><label>Input Data (JSON)<textarea value={input} onChange={(e) => setInput(e.target.value)} /></label><label className="checkbox"><input type="checkbox" checked={requiresApproval} onChange={(e) => setRequiresApproval(e.target.checked)} /> Требуется согласование</label><div className="actions"><button type="submit">Создать задачу</button><button type="button" className="secondary" onClick={() => router.back()}>Отмена</button></div></form></section></main>;
}
