"use client";
import { useState } from "react";
import Link from "next/link";
import { optimizationWorkspaceApi, type OptimizationProvenance, type ProvenanceNode } from "@/lib/optimization-workspace";
const detailLabels: Record<string, string> = {
 views: "Просмотры", impressions: "Показы", reactions: "Реакции", likes: "Лайки", comments: "Комментарии", shares: "Репосты", clicks: "Клики", subscribers: "Подписчики",
 channel: "Канал", observed_at: "Время наблюдения", source: "Источник", provider: "Провайдер", metrics: "Наблюдаемые метрики", category: "Категория", rating: "Оценка", published_at: "Опубликовано", scheduled_at: "Запланировано", version_number: "Версия",
 published_publication_count: "Опубликованные материалы", publications_with_metrics: "Публикации с метриками", human_feedback_count: "Отзывы", raw_metric_coverage: "Покрытие метрик",
};
function ReadableDetails({details}: {details: Record<string, unknown>}) {
 const entries = Object.entries(details).filter(([key]) => !key.endsWith("_id") && !key.endsWith("_ids") && key !== "source_target");
 const exactLinks = Object.entries(details).filter(([key]) => key.endsWith("_id") || key.endsWith("_ids"));
 return <><dl>{entries.map(([key, value]) => <div key={key}><dt>{detailLabels[key] ?? key}</dt><dd>{value == null ? "Нет данных" : typeof value === "object" && !Array.isArray(value) ? <ReadableDetails details={value as Record<string, unknown>} /> : typeof value === "object" ? JSON.stringify(value) : String(value)}</dd></div>)}</dl>{details.source_target === true && <p>Исходная версия цели изменения.</p>}{exactLinks.length > 0 && <details><summary>Точные сохранённые связи</summary><dl>{exactLinks.map(([key, value]) => <div key={key}><dt>{key}</dt><dd>{value == null ? "Связь не зафиксирована" : String(value)}</dd></div>)}</dl></details>}</>;
}
function Nodes({nodes}:{nodes:ProvenanceNode[]}) { return nodes.length ? <ul>{nodes.map(node => <li key={`${node.type}-${node.id}`}><strong>{node.href ? <Link href={node.href}>{node.title}</Link> : node.title}</strong>{node.status && <span> · {node.status}</span>}<small title={node.id}> · {node.id.slice(0, 8)}</small><ReadableDetails details={node.details}/></li>)}</ul> : <p>Ещё не создано</p>; }
export function OptimizationProvenanceView({actionId}:{actionId:string}) {
 const [data,setData]=useState<OptimizationProvenance|null>(null); const [open,setOpen]=useState(false); const [error,setError]=useState(""); const [busy,setBusy]=useState(false);
 async function show() { setOpen(true); if(data) return; setBusy(true); try {setData(await optimizationWorkspaceApi.provenance(actionId));} catch(e) {setError(e instanceof Error ? e.message : "Не удалось открыть provenance");} finally {setBusy(false);} }
 return <><button className="secondary" onClick={() => void show()} disabled={busy}>Почему предложено?</button>{open && <section className="provenance-view" aria-label="Почему предложено изменение"><button className="secondary" onClick={()=>setOpen(false)}>Закрыть цепочку</button>{busy && <p role="status">Загрузка сохранённых связей…</p>}{error && <p role="alert">{error}</p>}{data && <><h4>Evidence ↓ Analysis ↓ Recommendation ↓ Action ↓ Created artifact ↓ Content ↓ Publication</h4><h4>Evidence</h4><Nodes nodes={data.resolved_evidence}/><h4>Анализ</h4><Link href={`/campaigns/${data.campaign.id}/performance#analysis-${data.analysis.id}`}>Анализ результатов · {data.analysis.status} · стратегия v{data.analysis.strategy_version}</Link><p>Fingerprint: {data.analysis.evidence_fingerprint ?? "не указан"}</p><p>Период: {data.analysis.analysis_period_start ?? "не указан"} — {data.analysis.analysis_period_end ?? "не указан"}</p><p>Качество данных: {data.analysis.data_quality ? "Сохранено в снимке" : "не сохранено"}</p>{data.analysis.data_quality && <ReadableDetails details={data.analysis.data_quality}/>}<h4>Исходная рекомендация</h4><p>{data.source_recommendation.text ?? "Связь не зафиксирована"}</p><h4>Рекомендация к изменению</h4><p>{data.action.reason} · {data.action.expected_effect} · {data.action.status}</p><h4>Созданный artifact</h4><Nodes nodes={data.downstream_artifacts}/><h4>Точные версии контента</h4><Nodes nodes={data.content_versions}/><h4>Публикации</h4><Nodes nodes={data.publications}/>{data.limitations.map((gap,index)=><p className="notice" key={index}>Ограничение: {gap}</p>)}</>}</section>}</>;
}
