import { act, fireEvent, render, screen, within } from "@testing-library/react";
import { beforeEach, expect, it, vi } from "vitest";
import { CampaignKPIBlock, PublicationPerformanceTable } from "../components/campaign-kpis";
import type { CampaignKPI, CampaignPerformance, KPIEvaluation } from "../lib/api";
import { request } from "../lib/api";
const mocks = vi.hoisted(() => ({ list: vi.fn(), create: vi.fn(), update: vi.fn(), delete: vi.fn(), change: vi.fn() }));
vi.mock("@/lib/api", async original => ({ ...await original<object>(), campaignKpisApi: mocks }));
let rows: CampaignKPI[], fact: KPIEvaluation, performance: CampaignPerformance;
const kpi = { id: "kpi", campaign_id: "campaign", metric: "VIEWS", channel: null, target_value: "10", comparison: "GTE", period_start: "2026-10-01T00:00:00Z", period_end: "2026-10-10T00:00:00Z", description: null, is_active: true, created_at: "2026-10-01", updated_at: "2026-10-01" } as CampaignKPI;
beforeEach(() => {
 vi.clearAllMocks();rows=[];
 fact={kpi_id:"kpi",metric:"VIEWS",channel:null,target_value:"10",comparison:"GTE",period_start:kpi.period_start,period_end:kpi.period_end,observed_value:12,target_met:true,observed_publication_count:1,eligible_publication_count:2,coverage_ratio:.5,limitation:"Частичное покрытие"};
 performance={total_published:2,with_metrics:1,metric_coverage:{},totals:{views:12},kpis:[fact],publications:[{publication_id:"publication",content_item_id:"content",content_version_id:"exact-version",channel:"VK",published_at:"2026-10-02T00:00:00Z",metrics:null,views:0,impressions:null,reactions:2,comments:null,shares:1,clicks:0,source:"MANUAL",observed_at:"2026-10-03T00:00:00Z"}]};
 mocks.list.mockImplementation(async()=>structuredClone(rows));mocks.create.mockImplementation(async(_id,data)=>{rows=[{...kpi,...data}];return rows[0];});mocks.update.mockImplementation(async(_id,data)=>{rows=[{...rows[0],...data}];return rows[0];});mocks.delete.mockImplementation(async()=>{rows=[];});
});
async function ready(archived=false){render(<CampaignKPIBlock campaignId="campaign" archived={archived} performance={performance} onChange={mocks.change}/>);await screen.findByRole("heading",{name:"Цели кампании"});await act(async()=>{});}
function fill(){fireEvent.change(screen.getByLabelText("Начало периода (местное время)"),{target:{value:"2026-10-01T00:00"}});fireEvent.change(screen.getByLabelText("Конец периода (местное время)"),{target:{value:"2026-10-10T00:00"}});fireEvent.change(screen.getByLabelText("Целевое значение"),{target:{value:"10"}});}
it("empty state makes no mutations",async()=>{await ready();expect(screen.getByText("KPI пока не настроены.")).toBeInTheDocument();expect(mocks.create).not.toHaveBeenCalled();});
it("creates first KPI with aware ISO dates and explicit channel",async()=>{await ready();fireEvent.click(screen.getByText("Добавить KPI"));fill();fireEvent.change(screen.getByLabelText("Канал"),{target:{value:"VK"}});fireEvent.click(screen.getByText("Сохранить KPI"));await screen.findByText("VIEWS · VK");expect(mocks.create).toHaveBeenCalledWith("campaign",expect.objectContaining({channel:"VK",metric:"VIEWS",target_value:"10",period_start:expect.stringMatching(/Z$/)}));expect(mocks.change).toHaveBeenCalledOnce();});
it("edits existing config and preserves period",async()=>{rows=[kpi];await ready();fireEvent.click(screen.getByText("Редактировать KPI"));expect(screen.getByLabelText("Целевое значение")).toHaveValue(10);fireEvent.change(screen.getByLabelText("Целевое значение"),{target:{value:"20"}});fireEvent.click(screen.getByText("Сохранить KPI"));await screen.findByText(/Цель: ≥ 20/);expect(mocks.update).toHaveBeenCalledWith("kpi",expect.objectContaining({target_value:"20"}));expect(mocks.create).not.toHaveBeenCalled();});
it("deletes config explicitly",async()=>{rows=[kpi];await ready();fireEvent.click(screen.getByText("Удалить KPI"));await screen.findByText("KPI пока не настроены.");expect(mocks.delete).toHaveBeenCalledWith("kpi");});
it("five active prevents sixth",async()=>{rows=Array.from({length:5},(_,i)=>({...kpi,id:String(i)}));await ready();expect(screen.getByText("Добавить KPI")).toBeDisabled();expect(screen.getByText("Максимум пять активных KPI.")).toBeInTheDocument();});
it("inactive rows do not consume active limit",async()=>{rows=Array.from({length:5},(_,i)=>({...kpi,id:String(i),is_active:false}));await ready();expect(screen.getByText("Добавить KPI")).toBeEnabled();});
it("archived configuration is read only",async()=>{rows=[kpi];await ready(true);for(const label of ["Добавить KPI","Редактировать KPI","Удалить KPI"])expect(screen.getByText(label)).toBeDisabled();expect(mocks.update).not.toHaveBeenCalled();});
it("invalid ordering blocks submit",async()=>{await ready();fireEvent.click(screen.getByText("Добавить KPI"));fill();fireEvent.change(screen.getByLabelText("Конец периода (местное время)"),{target:{value:"2026-09-30T00:00"}});expect(screen.getByText("Сохранить KPI")).toBeDisabled();});
it("negative target blocks submit",async()=>{await ready();fireEvent.click(screen.getByText("Добавить KPI"));fill();fireEvent.change(screen.getByLabelText("Целевое значение"),{target:{value:"-1"}});expect(screen.getByText("Сохранить KPI")).toBeDisabled();});
it("duplicate submit protected",async()=>{await ready();fireEvent.click(screen.getByText("Добавить KPI"));fill();let resolve!:(value:CampaignKPI)=>void;mocks.create.mockImplementation(()=>new Promise(r=>{resolve=r;}));const button=screen.getByText("Сохранить KPI");fireEvent.click(button);fireEvent.click(button);expect(mocks.create).toHaveBeenCalledOnce();await act(async()=>resolve(kpi));});
it("request error preserves human configuration",async()=>{mocks.create.mockRejectedValue(new Error("Ошибка сохранения"));await ready();fireEvent.click(screen.getByText("Добавить KPI"));fill();fireEvent.click(screen.getByText("Сохранить KPI"));await screen.findByRole("alert");expect(screen.getByLabelText("Целевое значение")).toHaveValue(10);});
it.each([[true,"достигнута"],[false,"не достигнута"],[null,"недостаточно данных"]] as const)("target state %s",async(value,label)=>{rows=[kpi];fact.target_met=value;await ready();expect(screen.getByText(label)).toBeInTheDocument();});
it("fact target channel and coverage displayed",async()=>{rows=[kpi];await ready();expect(screen.getByText("VIEWS · Все каналы")).toBeInTheDocument();expect(screen.getByText(/Цель: ≥ 10 · Факт: 12/)).toBeInTheDocument();expect(screen.getByText("Покрытие: 1/2 (50%)")).toBeInTheDocument();expect(screen.getByText("Частичное покрытие")).toBeInTheDocument();});
it("derived KPI missing denominator unavailable",async()=>{rows=[{...kpi,metric:"CTR"}];fact.metric="CTR";fact.observed_value=null;fact.target_met=null;fact.coverage_ratio=0;fact.observed_publication_count=0;await ready();expect(screen.getByText(/Факт: Нет данных/)).toBeInTheDocument();expect(screen.getByText("недостаточно данных")).toBeInTheDocument();});
it("measured zero remains visible",async()=>{rows=[kpi];fact.observed_value=0;fact.target_met=false;await ready();expect(screen.getByText(/Факт: 0/)).toBeInTheDocument();});
it("reload retains config without resubmitting",async()=>{rows=[kpi];await ready();expect(screen.getByText("VIEWS · Все каналы")).toBeInTheDocument();expect(mocks.create).not.toHaveBeenCalled();});
it("publication table exact provenance and null versus zero",()=>{render(<PublicationPerformanceTable performance={performance}/>);const table=screen.getByRole("table");expect(within(table).getByText("exact-version")).toBeInTheDocument();expect(within(table).getByText("MANUAL")).toBeInTheDocument();expect(within(table).getByText("2026-10-03T00:00:00Z")).toBeInTheDocument();expect(within(table).getAllByText("0")).toHaveLength(2);expect(within(table).getAllByText("Нет данных")).toHaveLength(2);});
it("no invented overall score or AI control",async()=>{await ready();expect(screen.queryByText(/общий балл|overall score|автоматический анализ/i)).not.toBeInTheDocument();});
it("API handles successful DELETE 204 without JSON parsing",async()=>{const json=vi.fn();vi.stubGlobal("fetch",vi.fn().mockResolvedValue({ok:true,status:204,json}));try{expect(await request<void>("/campaign-kpis/kpi",{method:"DELETE"})).toBeUndefined();expect(json).not.toHaveBeenCalled();}finally{vi.unstubAllGlobals();}});
