import { fireEvent, render, screen, waitFor, within } from "@testing-library/react";
import { beforeEach, expect, it, vi } from "vitest";
import { OptimizationProposalPanel } from "../components/optimization-proposal";
import type { FeedbackAnalysis, OptimizationProposal } from "../lib/api";
const mocks = vi.hoisted(() => ({list:vi.fn(), get:vi.fn(), approve:vi.fn(), reject:vi.fn(), apply:vi.fn()}));
vi.mock("@/lib/api", async (original) => ({...await original<object>(), optimizationApi:mocks}));
const analysis={id:"analysis",campaign_id:"campaign",status:"ACCEPTED"} as FeedbackAnalysis;
let proposal:OptimizationProposal;
beforeEach(() => {
 vi.clearAllMocks();
 proposal={id:"proposal",campaign_id:"campaign",feedback_analysis_id:"analysis",strategy_version:7,status:"WAITING_APPROVAL",summary:"Summary",created_by_agent_run_id:"run",reviewed_by_user_id:null,reviewed_at:null,created_at:"2026-10-07",actions:[
 {id:"one",position:0,type:"CONTENT_REVISION",target_entity_type:"CONTENT_ITEM",target_entity_id:"content",target_version_id:"version",reason:"Уточнить аргумент",expected_effect:"Повысить ясность",priority:"HIGH",evidence_refs:[{type:"marketing_feedback",id:"feedback"}],status:"PROPOSED"},
 {id:"two",position:1,type:"NO_CHANGE",target_entity_type:"CAMPAIGN",target_entity_id:"campaign",target_version_id:null,reason:"Недостаточно доказательств",expected_effect:"Сохранить подход",priority:"LOW",evidence_refs:[],status:"PROPOSED"}]};
 mocks.list.mockImplementation(async()=>[structuredClone(proposal)]);mocks.get.mockImplementation(async()=>structuredClone(proposal));
 mocks.approve.mockImplementation(async(id)=>{proposal.actions.find(a=>a.id===id)!.status="APPROVED";});mocks.reject.mockImplementation(async(id)=>{proposal.actions.find(a=>a.id===id)!.status="REJECTED";});
});
async function ready(archived=false){render(<OptimizationProposalPanel analysis={analysis} archived={archived}/>);await screen.findByRole("heading",{name:"Рекомендации к изменениям"});}
it("loads accepted proposal with separate cards, target, reason, effect, priority and evidence",async()=>{
 await ready();expect(mocks.list).toHaveBeenCalledWith("campaign");const card=screen.getByRole("article",{name:"Доработка контента"});
 for(const text of ["Уточнить аргумент","Повысить ясность",/HIGH/,/Обратная связь: feedback/])expect(within(card).getByText(text)).toBeInTheDocument();expect(within(card).getByTitle("content")).toBeInTheDocument();expect(within(card).getByTitle("version")).toBeInTheDocument();expect(screen.getAllByRole("article")).toHaveLength(2);
});
it("approves one action and refreshes terminal decision",async()=>{
 await ready();fireEvent.click(within(screen.getByRole("article",{name:"Доработка контента"})).getByRole("button",{name:"Принять"}));await waitFor(()=>expect(mocks.get).toHaveBeenCalledWith("proposal"));
 const card=screen.getByRole("article",{name:"Доработка контента"});await within(card).findByText(/Принято/);for(const name of ["Принять","Отклонить"])expect(within(card).getByRole("button",{name})).toBeDisabled();expect(mocks.approve).toHaveBeenCalledWith("one");expect(mocks.reject).not.toHaveBeenCalled();expect(screen.getByRole("article",{name:"Без изменений"})).toHaveTextContent("Ожидает решения");
});
it("rejects one action without approving others",async()=>{await ready();fireEvent.click(within(screen.getByRole("article",{name:"Без изменений"})).getByRole("button",{name:"Отклонить"}));await waitFor(()=>expect(mocks.reject).toHaveBeenCalledWith("two"));await within(screen.getByRole("article",{name:"Без изменений"})).findByText(/Отклонено/);expect(mocks.approve).not.toHaveBeenCalled();});
it("persists terminal state after page reload",async()=>{proposal.actions[0].status="APPROVED";const view=render(<OptimizationProposalPanel analysis={analysis} archived={false}/>);await screen.findByText(/Принято/);view.unmount();await ready();for(const name of ["Принять","Отклонить"])expect(within(screen.getByRole("article",{name:"Доработка контента"})).getByRole("button",{name})).toBeDisabled();});
it("legacy has no fabricated proposal UI",async()=>{mocks.list.mockResolvedValue([]);const{container}=render(<OptimizationProposalPanel analysis={analysis} archived={false}/>);await waitFor(()=>expect(mocks.list).toHaveBeenCalled());expect(container).toBeEmptyDOMElement();});
it("shows advisory notice with no bulk or Apply controls",async()=>{await ready();expect(screen.getByText(/Принятие рекомендации фиксирует решение/)).toBeInTheDocument();for(const name of ["Принять всё","Применить","Изменить стратегию","Создать задачу","Пересобрать медиаплан","Создать эксперимент","Опубликовать"])expect(screen.queryByRole("button",{name})).not.toBeInTheDocument();});
it("archived is read only",async()=>{await ready(true);for(const button of screen.getAllByRole("button").filter(button => button.textContent !== "Почему предложено?").filter(button => button.textContent !== "Почему предложено?"))expect(button).toBeDisabled();});
it("renders untrusted reason as text and no arbitrary links",async()=>{proposal.actions[0].reason='<a href="https://evil.test">change</a>';await ready();expect(screen.getByText(proposal.actions[0].reason)).toBeInTheDocument();expect(screen.queryByRole("link")).not.toBeInTheDocument();});
it("load failure visible rather than treated as legacy",async()=>{mocks.list.mockRejectedValue(new Error("Load failed"));render(<OptimizationProposalPanel analysis={analysis} archived={false}/>);await screen.findByRole("alert");});
it("decision failure produces no optimistic success or automatic retry",async()=>{mocks.approve.mockRejectedValue(new Error("Conflict"));await ready();fireEvent.click(within(screen.getByRole("article",{name:"Доработка контента"})).getByRole("button",{name:"Принять"}));await screen.findByRole("alert");expect(mocks.approve).toHaveBeenCalledTimes(1);expect(mocks.get).not.toHaveBeenCalled();expect(screen.getAllByText(/Ожидает решения/)).toHaveLength(2);});
const artifact = {artifact_type:"TASK" as const,artifact_id:"task",task_id:"task",publication_plan_id:null,agent_run_id:"run",status:"READY",href:"/tasks/task",error_message:null};
function approved(){proposal.actions[0].status="APPROVED";}
function completed(status="READY"){proposal.actions[0].status="APPLIED";proposal.actions[0].applied_artifact={...artifact,status,error_message:status==="FAILED"?"Generation failed":null};proposal.status="APPLIED";}
async function confirm(){fireEvent.click(screen.getByRole("button",{name:"Применить"}));fireEvent.change(screen.getByRole("textbox"),{target:{value:"Human"}});fireEvent.click(screen.getByRole("button",{name:"Подтвердить применение"}));}
it.each(["CONTENT_REVISION","PUBLICATION_PLAN_REVISION","STRATEGY_REVIEW"] as const)("Apply only for approved %s",async type=>{approved();proposal.actions[0].type=type;await ready();expect(screen.getByRole("button",{name:"Применить"})).toBeEnabled();expect(mocks.apply).not.toHaveBeenCalled();});
it.each(["PROPOSED","REJECTED","APPLIED","FAILED"] as const)("no Apply for %s",async status=>{proposal.actions[0].status=status;await ready();expect(screen.queryByRole("button",{name:"Применить"})).not.toBeInTheDocument();});
it.each(["NO_CHANGE","EXPERIMENT"] as const)("no Apply for approved %s",async type=>{approved();proposal.actions[0].type=type;await ready();expect(screen.queryByRole("button",{name:"Применить"})).not.toBeInTheDocument();expect(screen.getByText(type==="NO_CHANGE"?"Изменения не требуются.":"Для этой старой рекомендации отсутствуют структурированные параметры эксперимента. Сформируйте новый анализ на актуальных данных.")).toBeInTheDocument();});
it("requires human comment and warning without model prefill",async()=>{approved();await ready();fireEvent.click(screen.getByRole("button",{name:"Применить"}));const comment=screen.getByRole("textbox",{name:/Комментарий человека/});expect(comment).toHaveValue("");expect(screen.getByText(/Текущая утверждённая версия останется действующей/)).toBeInTheDocument();const button=screen.getByRole("button",{name:"Подтвердить применение"});expect(button).toBeDisabled();fireEvent.change(comment,{target:{value:"   "}});expect(button).toBeDisabled();fireEvent.change(comment,{target:{value:"Human"}});expect(button).toBeEnabled();});
it("applies once and links artifact without auto approval",async()=>{approved();mocks.apply.mockImplementation(async()=>{completed();return{...artifact,action:proposal.actions[0]};});await ready();await confirm();await screen.findByRole("link",{name:"Открыть задачу"});expect(mocks.apply).toHaveBeenCalledExactlyOnceWith("one","Human");expect(mocks.approve).not.toHaveBeenCalled();expect(mocks.reject).not.toHaveBeenCalled();expect(screen.getByText(/Статус workflow: READY/)).toBeInTheDocument();expect(screen.queryByRole("button",{name:"Применить"})).not.toBeInTheDocument();});
it("reload persists link and downstream failure",async()=>{completed("FAILED");const view=render(<OptimizationProposalPanel analysis={analysis} archived={false}/>);await screen.findByRole("link",{name:"Открыть задачу"});await screen.findByText("Generation failed");view.unmount();await ready();expect(screen.getByRole("link",{name:"Открыть задачу"})).toHaveAttribute("href","/tasks/task");expect(screen.getByText(/Статус workflow: FAILED/)).toBeInTheDocument();expect(mocks.apply).not.toHaveBeenCalled();});
it("blocks repeated click while busy",async()=>{approved();let finish!:()=>void;mocks.apply.mockImplementation(()=>new Promise(resolve=>{finish=()=>{completed();resolve({...artifact,action:proposal.actions[0]});};}));await ready();await confirm();const button=screen.getByRole("button",{name:"Подтвердить применение"});fireEvent.click(button);expect(mocks.apply).toHaveBeenCalledTimes(1);expect(button).toBeDisabled();finish();await screen.findByRole("link",{name:"Открыть задачу"});});
it("shows conflict without optimistic application or retry",async()=>{approved();mocks.apply.mockRejectedValue(new Error("Frozen target stale"));await ready();await confirm();await screen.findByRole("alert");expect(screen.getByText("Frozen target stale")).toBeInTheDocument();expect(mocks.apply).toHaveBeenCalledTimes(1);expect(screen.queryByRole("link")).not.toBeInTheDocument();});
it("optional strategy comment still needs confirmation",async()=>{approved();proposal.actions[0].type="STRATEGY_REVIEW";await ready();fireEvent.click(screen.getByRole("button",{name:"Применить"}));expect(screen.getByRole("button",{name:"Подтвердить применение"})).toBeEnabled();expect(mocks.apply).not.toHaveBeenCalled();expect(screen.queryByRole("button",{name:"Apply All"})).not.toBeInTheDocument();});
