/** Local UI acceptance fixtures. No DB, broker, credentials or upstream network calls.
 * Run: node scripts/acceptance/ui_fixture_api.mjs
 * Frontend: NEXT_PUBLIC_API_URL=http://localhost:8101/api/v1 npm run dev -- --port 3001
 * In-memory state only; restart to reset. Never point this fixture API at a real runtime.
 */
import { createServer } from 'node:http';
const now = '2026-10-05T12:00:00Z';
const campaign = {id:'campaign-fixture',name:'UI acceptance campaign',goal:'Проверить путь оператора',product:'Fixture',status:'ACTIVE',start_date:now,end_date:'2026-11-01T12:00:00Z',created_at:now,updated_at:now,strategy:null,strategy_version:1,creator:{id:'user-fixture',full_name:'Fixture Operator',email:'fixture@example.test'}};
const agent = {id:'smm-fixture',name:'SMM Manager',slug:'smm_manager',role:'smm_manager',status:'ACTIVE',model:'mock',autonomy_level:2};
const planItem = {id:'item-fixture',position:1,status:'PLANNED',scheduled_at:'2026-10-20T12:00:00Z',channel:'VK',topic:'Новый пост по медиаплану',angle:'Практический пример',purpose:'Проверить UI',format:'post',message_brief:'Только fixture. Никаких provider calls.',source_content_item_id:'article-fixture',source_content_version_id:'article-v1',source_content_item_title:'Утверждённая статья',source_version_number:1,source_claim_ids:['claim-fixture'],source_support_summary:'Fixture sources',near_publication_warnings:[]};
const plan = {id:'plan-fixture',campaign_id:campaign.id,status:'APPROVED',planning_horizon_start:now,planning_horizon_end:'2026-11-01T12:00:00Z',timezone_policy:'UTC',items:[planItem],generated_by_agent_run_id:null};
const article = {id:'article-fixture',campaign_id:campaign.id,title:'Утверждённая статья',content_type:'ARTICLE',status:'APPROVED',current_version_id:'article-v1',approved_version_id:'article-v1',current_version_number:1,approved_version_number:1,created_at:now,updated_at:now,source_task_id:'source-fixture',source_task_title:'Источник fixture',plan_item_count:1,social_post_count:0,scheduled_publication_count:0,published_count:0};
const version = {id:'post-v1',content_item_id:'post-fixture',version_number:1,content:'Текст fixture для проверки поста. Решения требуют проверки человеком.',structured_content:{text_markdown:'Текст fixture для проверки поста.',cta:'Проверить результат',sources:[]},sources:[],derivations:[],created_at:now};
const post = {id:'post-fixture',campaign_id:campaign.id,title:'Пост для согласования',content_type:'SOCIAL_POST',status:'WAITING_APPROVAL',current_version_id:version.id,approved_version_id:null,current_version_number:1,approved_version_number:null,channel:'VK',plan_channel:'VK',plan_scheduled_at:planItem.scheduled_at,publication_plan_item_id:planItem.id,source_task_id:'task-fixture',source_content_item_title:article.title,created_at:now,updated_at:now,current_version:version,versions:[version],metadata:{publication_plan_item_id:planItem.id}};
const publications=[];const approvals=[];let task=null;let createdAt=0;let revision=null;let mode='normal';let requests=[];
function detail(){return {...post,current_version:post.versions.find(v=>v.id===post.current_version_id),approval_history:approvals,children:[]};}
function tick(){if(!task)return;const age=Date.now()-createdAt;task.status=age<6000?'READY':age<10000?'READY':age<14000?'IN_PROGRESS':'COMPLETED';if(age>=14000){task.output_data={content_item_id:post.id};if(revision && revision.task_status!=='COMPLETED'){const v={...version,id:`post-v${post.versions.length+1}`,version_number:post.versions.length+1,content:'Mock AI revision. No provider calls.'};post.versions.push(v);post.current_version_id=v.id;post.current_version_number=v.version_number;post.status='WAITING_APPROVAL';revision={...revision,task_status:'COMPLETED',agent_run_status:'COMPLETED',agent_run_id:'run-fixture',created_content_version_id:v.id};}}}
function runs(){tick();if(!task||Date.now()-createdAt<6000)return [];return [{id:'run-fixture',task_id:task.id,agent_id:agent.id,campaign_id:campaign.id,status:task.status==='READY'?'QUEUED':task.status==='IN_PROGRESS'?'RUNNING':'COMPLETED',model:'mock',created_at:now,agent}];}
function allContent(){tick();return task?.status==='COMPLETED'||revision?[article,post]:[article];}
function workspace(){const content=allContent();const posts=content.filter(c=>c.content_type==='SOCIAL_POST');return {campaign,director:{strategy_status:'ACTIVE',article_count:1,approved_article_count:1,plan_status:'APPROVED',plan_item_count:1,plan_items_with_posts:posts.length,plan_items_without_posts:1-posts.length,social_post_count:posts.length,posts_waiting_approval:post.status==='WAITING_APPROVAL'?posts.length:0,scheduled_publication_count:publications.filter(p=>p.status==='SCHEDULED').length,published_count:0,failed_task_count:0,blocked_task_count:0,next_step:{title:posts.length?'Проверить пост':'Создать VK-пост для пункта №1',description:'Fixture-only operator journey',href:posts.length?`/content/${post.id}#approval`:`/campaigns/${campaign.id}#plan-item-${planItem.id}`,entity_type:'publication_plan_item',entity_id:planItem.id}},knowledge:{store_ready:true,source_count:1,item_count:1,ready_item_count:1,processing_item_count:0,failed_item_count:0,campaign_packs:[],has_current_strategy_pack:true},articles:[article],social_posts:posts,publication_plan:{...plan,item_count:1,items:[{...planItem,social_posts:posts,publications,pipeline:[{label:'Статья',status:'available',href:`/content/${article.id}`,action_label:'v1'},{label:'Пост',status:posts.length?'created':'not_created',href:posts.length?`/content/${post.id}`:`/campaigns/${campaign.id}#plan-item-${planItem.id}`,action_label:'Создать пост'}],post_action:{allowed:!task,existing_task_id:task?.id??null,error_code:null,reason:null,next_action:null}}]},other_plans:[],publications,attention_tasks:task?[task]:[],feedback:{new_feedback_count:0,new_metrics_count:0}};}
function newTask(type='CREATE_SOCIAL_POSTS'){createdAt=Date.now();task={id:'task-fixture',campaign_id:campaign.id,campaign:{id:campaign.id,name:campaign.name},task_type:type,title:'Создать fixture пост',assigned_agent:agent,assigned_agent_id:agent.id,status:'READY',classification:'actionable',priority:'NORMAL',input_data:{publication_plan_item_id:planItem.id},output_data:{},dependencies:[],dependents:[],created_at:now,updated_at:now,retry_count:0};return task;}
function response(path,method,body){
 tick();
 if(path==='/__fixture/status')return {mode,requests,provider_calls:0,task_count:task?1:0};
 if(path==='/__fixture/mode'&&method==='POST'){mode=body.mode;return {mode};}
 if(mode==='error'&&path!=='/auth/me')throw new Error('Fixture network error');
 if(path==='/auth/me')return {id:'user-fixture',email:'fixture@example.test',full_name:'Fixture Operator',role:'ADMIN',is_active:true};
 if(path==='/campaigns')return mode==='empty'?[]:[campaign];
 if(path===`/campaigns/${campaign.id}`)return campaign;
 if(path.endsWith('/workspace'))return workspace();
 if(path==='/agents')return [agent];
 if(path==='/tasks'&&method==='POST')return newTask();
 if(path==='/tasks')return task?[task]:[];
 if(path.startsWith('/tasks/')){if(method!=='GET')throw new Error('Manual execution forbidden in fixture');return path.includes('source-fixture') ? {id:'source-fixture',campaign_id:campaign.id,campaign:{id:campaign.id,name:campaign.name},task_type:'MANUAL',title:'Источник fixture',status:'COMPLETED',priority:'NORMAL',input_data:{},output_data:{},dependencies:[],dependents:[],created_at:now,updated_at:now} : task;}
 if(path==='/agent-runs')return runs();
 if(path==='/content')return mode==='empty'?[]:allContent();
 if(path.endsWith('/revision-status'))return revision;
 if(path===`/content/${post.id}/manual-edit`&&method==='POST'){if(body.expected_current_version_id!==post.current_version_id)throw new Error('STALE_CONTENT_VERSION');const v={...version,id:`post-v${post.versions.length+1}`,version_number:post.versions.length+1,content:body.content,structured_content:{text_markdown:body.content}};post.versions.push(v);post.current_version_id=v.id;post.current_version_number=v.version_number;post.status='WAITING_APPROVAL';return detail();}
 if(path===`/content/${post.id}/approve`&&method==='POST'){post.status='APPROVED';post.approved_version_id=post.current_version_id;post.approved_version_number=post.current_version_number;approvals.unshift({id:`approval-${approvals.length}`,object_type:'CONTENT_ITEM',object_id:post.id,subject_version:post.current_version_number,status:'APPROVED',subject_snapshot:{content_version_id:post.current_version_id},created_at:now});return detail();}
 if(path===`/content/${post.id}/request-revision`&&method==='POST'){newTask('CONTENT_REVISION');revision={content_item_id:post.id,task_id:task.id,task_status:'READY',agent_run_id:null,agent_run_status:null,executor_available:true};return detail();}
 if(path===`/content/${post.id}`)return detail();
 if(path===`/content/${article.id}`)return {...article,current_version:{...version,id:'article-v1',content_item_id:article.id},versions:[],children:[],approval_history:[]};
 if(path==='/approvals')return approvals;
 if(path.endsWith('/publication-plans')||path.startsWith('/publication-plans/campaign/'))return [plan];
 if(path===`/publications/plan-content/${post.id}/schedule`&&method==='POST'){if(post.approved_version_id!==post.current_version_id)throw new Error('EXACT_APPROVAL_REQUIRED');const p={id:'pub-fixture',content_item_id:post.id,content_version_id:post.approved_version_id,campaign_id:campaign.id,channel:'VK',status:'SCHEDULED',scheduled_at:planItem.scheduled_at,published_at:null,external_url:null,provider_enabled:false,retry_allowed:false,reconciliation_required:false,publication_plan_item_id:planItem.id,created_at:now,updated_at:now};publications.splice(0,publications.length,p);return p;}
 if(path==='/publications/pub-fixture/replace-scheduled-version'&&method==='POST'){const p=publications[0];if(!p||p.status!=='SCHEDULED'||post.approved_version_id!==post.current_version_id)throw new Error('EXACT_APPROVAL_REQUIRED');p.content_version_id=post.approved_version_id;return p;}
 if(path.startsWith('/publications/campaign/'))return path.endsWith('/calendar')?publications.map(p=>({...p,publication_id:p.id,title:post.title})):publications;
 if(path==='/knowledge/store')return {id:'store-fixture',name:'Fixture store',status:'ACTIVE',is_active:true};
 if(path==='/knowledge/sources')return [{id:'source-fixture',name:'Fixture source',source_type:'FILE_UPLOAD',status:'ACTIVE'}];
 if(path==='/knowledge/items')return [{id:'knowledge-fixture',source_id:'source-fixture',title:'Fixture knowledge',content_type:'text',status:'READY',created_at:now,indexed_at:now,metadata:{}}];
 if(path==='/knowledge-packs')return [];
 if(path.endsWith('/performance'))return {total_published:0,with_metrics:0,totals:{},metric_coverage:{},publications:[]};
 if(path.includes('/feedback')||path.includes('/activities'))return [];
 if(path==='/system/status')return {tasks:{READY:0,IN_PROGRESS:0,FAILED:0},agent_runs:{RUNNING:0,FAILED:0},publications:{reconciliation_required:0,failed:0},stuck_tasks:0,pending_approvals:0};
 throw new Error(`Unsupported fixture route: ${method} ${path}`);
}
createServer(async(req,res)=>{const url=new URL(req.url,'http://127.0.0.1:8101');res.setHeader('Access-Control-Allow-Origin','http://localhost:3001');res.setHeader('Access-Control-Allow-Credentials','true');res.setHeader('Access-Control-Allow-Headers','Content-Type');res.setHeader('Access-Control-Allow-Methods','GET,POST,PATCH,OPTIONS');res.setHeader('Content-Type','application/json');if(req.method==='OPTIONS'){res.writeHead(204);res.end();return;}let raw='';for await(const chunk of req)raw+=chunk;try{const path=url.pathname.replace(/^\/api\/v1/,'');requests.push({method:req.method,path});res.end(JSON.stringify(response(path,req.method,raw?JSON.parse(raw):{})));}catch(error){res.writeHead(503);res.end(JSON.stringify({error:{code:'FIXTURE_ERROR',message:error.message}}));}}).listen(8101,'127.0.0.1',()=>console.log('Fixture API on 127.0.0.1:8101; no providers or databases'));
