"use client";

import Link from "next/link";
import { useParams, useRouter } from "next/navigation";
import { useCallback, useEffect, useRef, useState } from "react";

import { useAuth } from "@/components/auth-provider";
import { activitiesApi, approvalsApi, campaignsApi, contentApi, publicationsApi, tasksApi, type Activity, type Approval, type Campaign, type ContentListItem, type Publication, type PublicationCalendarItem, type TaskListItem } from "@/lib/api";
import { CAMPAIGN_STATUS_LABELS, formatDate, formatDateTime } from "@/lib/campaigns";
import { TASK_STATUS_LABELS } from "@/lib/tasks";

export default function CampaignDetailsPage() {
  const { id } = useParams<{ id: string }>(); const router = useRouter(); const { user, loading: authLoading } = useAuth();
  const [campaign, setCampaign] = useState<Campaign | null>(null); const [error, setError] = useState("");
  const [tasks, setTasks] = useState<TaskListItem[]>([]); const [approvals, setApprovals] = useState<Approval[]>([]); const [contents, setContents] = useState<ContentListItem[]>([]); const [publications, setPublications] = useState<Publication[]>([]); const [calendarItems, setCalendarItems] = useState<PublicationCalendarItem[]>([]); const [activities, setActivities] = useState<Activity[]>([]); const [action, setAction] = useState<"revision" | "reject" | null>(null); const [comment, setComment] = useState(""); const [publicationPollingMessage, setPublicationPollingMessage] = useState("");
  const publicationPollingStartedAt = useRef<number | null>(null);
  const load = useCallback(() => { void Promise.all([campaignsApi.get(id), tasksApi.list({ campaign_id: id }), approvalsApi.list({ object_type: "CAMPAIGN_STRATEGY", object_id: id }), contentApi.list({ campaign_id: id }), activitiesApi.list(id).catch(() => [])]).then(([campaignValue, taskRows, approvalRows, contentRows, activityRows]) => { setCampaign(campaignValue); setTasks(taskRows); setApprovals(approvalRows); setContents(contentRows); setActivities(activityRows); }).catch((reason: Error) => setError(reason.message)); void publicationsApi.listCampaign(id).then(setPublications).catch(() => setPublications([])); const from = new Date(); const to = new Date(from.getTime() + 90 * 24 * 60 * 60 * 1000); const calendarRequest = publicationsApi.calendar?.(id, from.toISOString(), to.toISOString()); if (calendarRequest) void calendarRequest.then(setCalendarItems).catch(() => setCalendarItems([])); }, [id]);
  useEffect(() => { if (!authLoading && !user) { router.replace("/login"); return; } if (user) load(); }, [authLoading, user, router, load]);
  useEffect(() => { if (campaign?.status !== "PLANNING") return; const timer = window.setInterval(load, 3000); return () => window.clearInterval(timer); }, [campaign?.status, load]);
  const hasPublishingPublication = publications.some((publication) => publication.status === "PUBLISHING");
  useEffect(() => {
    if (!hasPublishingPublication) { publicationPollingStartedAt.current = null; return; }
    if (publicationPollingStartedAt.current === null) publicationPollingStartedAt.current = Date.now();
    const timer = window.setInterval(() => {
      if (Date.now() - (publicationPollingStartedAt.current ?? Date.now()) >= 30_000) {
        window.clearInterval(timer); setPublicationPollingMessage("Статус доставки всё ещё подтверждается."); return;
      }
      void publicationsApi.listCampaign(id).then(setPublications).catch(() => undefined);
    }, 2_000);
    return () => window.clearInterval(timer);
  }, [hasPublishingPublication, id]);
  async function archive() { if (!window.confirm("Архивировать кампанию? После архивации редактирование будет недоступно.")) return; try { setCampaign(await campaignsApi.archive(id)); } catch (reason) { setError(reason instanceof Error ? reason.message : "Не удалось архивировать кампанию."); } }
  async function generate() { try { await campaignsApi.generateStrategy(id); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Не удалось сформировать стратегию."); } }
  async function approve() { try { await campaignsApi.approveStrategy(id); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Не удалось согласовать стратегию."); } }
  async function submitDecision() { if (!action || !comment.trim()) { setError("Комментарий обязателен."); return; } try { if (action === "revision") await campaignsApi.requestStrategyRevision(id, comment); else await campaignsApi.rejectStrategy(id, comment); setAction(null); setComment(""); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Не удалось сохранить решение."); } }
  async function preparePublication(item: ContentListItem) { try { const detail = await contentApi.get(item.id); if (!detail.approved_version_id || !item.channel) throw new Error("У материала отсутствует согласованная версия или канал."); await publicationsApi.create({ content_item_id: item.id, content_version_id: detail.approved_version_id, channel: item.channel }); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Не удалось подготовить публикацию."); } }
  async function approvePublication(publicationId: string) { try { await publicationsApi.approve(publicationId); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Не удалось согласовать публикацию."); } }
  async function schedulePublication(publicationId: string) { const value = window.prompt("Дата и время публикации (ISO или локальное время браузера)"); if (!value) return; const parsed = new Date(value); if (Number.isNaN(parsed.getTime())) { setError("Укажите корректные дату и время."); return; } try { await publicationsApi.schedule(publicationId, parsed.toISOString()); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Не удалось назначить публикацию."); } }
  async function cancelPublication(publicationId: string) { if (!window.confirm("Отменить публикацию?")) return; try { await publicationsApi.cancel(publicationId); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Не удалось отменить публикацию."); } }
  async function publishNow(publicationId: string) { try { await publicationsApi.publishNow(publicationId); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Не удалось поставить публикацию в очередь."); } }
  async function retryPublication(publicationId: string) { try { await publicationsApi.retry(publicationId); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Не удалось повторить публикацию."); } }
  async function reconcilePublished(publicationId: string) { const externalId = window.prompt("Внешний ID публикации"); if (!externalId?.trim()) return; const externalUrl = window.prompt("Внешняя ссылка (необязательно)") ?? ""; const publishedAt = window.prompt("Время внешней публикации ISO (необязательно)") ?? ""; const note = window.prompt("Комментарий (необязательно)") ?? ""; try { await publicationsApi.reconcilePublished(publicationId, { external_id: externalId.trim(), external_url: externalUrl || undefined, published_at: publishedAt || undefined, note: note || undefined }); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Не удалось подтвердить публикацию."); } }
  async function reconcileNotPublished(publicationId: string) { if (!window.confirm("Подтвердить, что внешней публикации нет?")) return; const note = window.prompt("Комментарий (необязательно)") ?? ""; try { await publicationsApi.reconcileNotPublished(publicationId, note || undefined); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Не удалось завершить сверку."); } }
  if (authLoading || (!campaign && !error)) return <main><p>Загружаем кампанию…</p></main>;
  if (!campaign) return <main><section><p role="alert" className="error">{error}</p><Link href="/campaigns">К кампаниям</Link></section></main>;
  const archived = campaign.status === "ARCHIVED";
  const upcoming = calendarItems.filter((item) => item.status === "SCHEDULED" && item.scheduled_at).sort((a, b) => new Date(a.scheduled_at ?? 0).getTime() - new Date(b.scheduled_at ?? 0).getTime()).slice(0, 10);
  const calendarGroups = calendarItems.reduce<Record<string, PublicationCalendarItem[]>>((groups, item) => { const date = new Date(item.scheduled_at ?? item.published_at ?? "").toLocaleDateString("ru-RU"); (groups[date] ??= []).push(item); return groups; }, {});
  return <main><section className="wide"><header className="page-header"><div><p className="eyebrow">Обзор</p><h1>{campaign.name}</h1><p className="status-text">{CAMPAIGN_STATUS_LABELS[campaign.status]}</p></div><Link href="/campaigns">К кампаниям</Link></header>
    {error && <p role="alert" className="error">{error}</p>}{hasPublishingPublication && publicationPollingMessage && <p role="status">{publicationPollingMessage}</p>}<div className="details-grid"><div><dt>Цель</dt><dd>{campaign.goal}</dd></div><div><dt>Продукт</dt><dd>{campaign.product ?? "Не указан"}</dd></div><div><dt>Целевая аудитория</dt><dd>{campaign.target_audience ?? "Не указана"}</dd></div><div><dt>Оффер</dt><dd>{campaign.offer ?? "Не указан"}</dd></div><div><dt>Желаемый результат</dt><dd>{campaign.desired_result ?? "Не указан"}</dd></div><div><dt>Период</dt><dd>{formatDate(campaign.start_date)} — {formatDate(campaign.end_date)}</dd></div><div><dt>Описание</dt><dd>{campaign.description ?? "Нет дополнительного контекста"}</dd></div><div><dt>Кто создал</dt><dd>{campaign.creator.full_name ?? campaign.creator.email}</dd></div><div><dt>Создана</dt><dd>{formatDateTime(campaign.created_at)}</dd></div><div><dt>Изменена</dt><dd>{formatDateTime(campaign.updated_at)}</dd></div></div>
    {!archived && <div className="actions"><Link className="button-link" href={`/campaigns/${id}/edit`}>Редактировать</Link><button className="secondary" onClick={archive}>Архивировать</button></div>}
    <div className="page-header"><h2>Стратегия</h2><span>Версия {campaign.strategy_version}</span></div>
    {campaign.status === "DRAFT" && <div><p>Стратегия ещё не сформирована.</p><button onClick={generate}>Сформировать стратегию</button></div>}
    {campaign.status === "PLANNING" && <div><p>AI-директор формирует стратегию...</p>{tasks.filter((item) => item.task_type === "CAMPAIGN_PLANNING").slice(0, 1).map((item) => <p key={item.id}>Задача: {TASK_STATUS_LABELS[item.status]}</p>)}</div>}
    {campaign.strategy && <div className="strategy"><h3>Резюме</h3><p>{campaign.strategy.campaign_summary}</p><h3>Позиционирование</h3><p>{campaign.strategy.positioning}</p><h3>Целевая аудитория</h3><p>{campaign.strategy.target_audience}</p><h3>Главное сообщение</h3><p>{campaign.strategy.main_message}</p><h3>Контент-стратегия</h3><p>{campaign.strategy.content_strategy}</p><h3>Темы контента</h3><ul>{campaign.strategy.content_topics.map((topic) => <li key={topic}>{topic}</li>)}</ul><h3>Основная статья</h3><p><strong>{campaign.strategy.recommended_article.title}</strong> — {campaign.strategy.recommended_article.objective}</p><h3>SMM-стратегия</h3><p>{campaign.strategy.social_strategy.approach} ({campaign.strategy.social_strategy.post_count} публикаций: {campaign.strategy.social_strategy.channels.join(", ")})</p><h3>План задач</h3><ol>{campaign.strategy.tasks.map((item) => <li key={item.key}><strong>{item.title}</strong> — {item.agent_slug}{item.depends_on.length ? `; зависит от: ${item.depends_on.join(", ")}` : ""}</li>)}</ol></div>}
    {campaign.status === "WAITING_APPROVAL" && <div className="actions"><button onClick={approve}>Утвердить стратегию</button><button className="secondary" onClick={() => setAction("revision")}>Запросить доработку</button><button className="secondary" onClick={() => setAction("reject")}>Отклонить</button></div>}
    {action && <div><label htmlFor="strategy-comment">{action === "revision" ? "Что необходимо изменить?" : "Причина отклонения"}</label><textarea id="strategy-comment" value={comment} onChange={(event) => setComment(event.target.value)} /><div className="actions"><button onClick={submitDecision}>Отправить</button><button className="secondary" onClick={() => setAction(null)}>Отмена</button></div></div>}
    {campaign.status === "ACTIVE" && <p><strong>Стратегия утверждена.</strong> Версия {campaign.strategy_version}.</p>}
    <h3>История согласования</h3>{approvals.length ? <ul>{approvals.map((approval) => <li key={approval.id}>Версия {approval.subject_version}: {approval.status}{approval.resolved_at ? ` — ${formatDateTime(approval.resolved_at)}` : ""}{approval.comment && <p>Комментарий: {approval.comment}</p>}</li>)}</ul> : <p>Согласований пока нет.</p>}
    <div className="page-header"><h2>Задачи</h2>{!archived && <Link className="button-link" href={`/tasks/new?campaign_id=${id}`}>Создать задачу</Link>}</div>
    <div className="summary-grid"><div><strong>{tasks.length}</strong><span>Всего</span></div><div><strong>{tasks.filter((item) => item.status === "READY").length}</strong><span>Ready</span></div><div><strong>{tasks.filter((item) => item.status === "BLOCKED").length}</strong><span>Blocked</span></div><div><strong>{tasks.filter((item) => item.status === "IN_PROGRESS").length}</strong><span>In Progress</span></div><div><strong>{tasks.filter((item) => item.status === "COMPLETED").length}</strong><span>Completed</span></div></div>
    {tasks.length ? <ul>{tasks.map((task) => <li key={task.id}><Link href={`/tasks/${task.id}`}>{task.title}</Link> — {TASK_STATUS_LABELS[task.status]}</li>)}</ul> : <p>У кампании пока нет задач.</p>}
    <h3>Ход workflow</h3><ol>{(["KNOWLEDGE_RESEARCH", "WRITE_ARTICLE", "CREATE_SOCIAL_POSTS"] as const).map((type) => { const task = tasks.find((item) => item.task_type === type); return <li key={type}>{type}: {task ? TASK_STATUS_LABELS[task.status] : "—"}</li>; })}</ol>
    <div className="page-header"><h2>Контент</h2><span>Ожидают согласования: {contents.filter((item) => item.status === "WAITING_APPROVAL").length}</span></div>
    {contents.length ? <ul>{contents.map((item) => <li key={item.id}><Link href={`/content/${item.id}`}>{item.title}</Link> — {item.content_type} · {item.status}{item.content_type === "SOCIAL_POST_PACK" && <span> · постов: {contents.filter((child) => child.parent_content_item_id === item.id).length}</span>}</li>)}</ul> : <p>Контент ещё не создан.</p>}
    <div className="page-header"><h2>Публикации</h2><span>Внешняя отправка выполняется worker-ом</span></div>
    {contents.filter((item) => item.content_type === "SOCIAL_POST").map((item) => { const publication = publications.find((row) => row.content_item_id === item.id); return <div key={item.id} className="card"><p><strong>{item.title}</strong> · {item.channel ?? "—"}</p>{publication ? <div><p>Статус публикации: {publication.status}{publication.scheduled_at ? ` · ${formatDateTime(publication.scheduled_at)}` : ""}{publication.external_url ? <> {" · "}<a href={publication.external_url} target="_blank" rel="noreferrer">Открыть во внешнем сервисе</a></> : ""}</p>{publication.reconciliation_required && <><p role="alert">Требуется сверка факта доставки.</p><button onClick={() => reconcilePublished(publication.id)}>Подтвердить публикацию</button><button className="secondary" onClick={() => reconcileNotPublished(publication.id)}>Подтвердить отсутствие публикации</button></>}{publication.status === "PUBLISHING" && <p role="status">Статус доставки не подтверждён.</p>}{["DRAFT", "WAITING_APPROVAL"].includes(publication.status) && <button onClick={() => approvePublication(publication.id)}>Согласовать публикацию</button>}{publication.status === "APPROVED" && (publication.channel === "TELEGRAM" || publication.channel === "VK") && publication.provider_enabled !== false && <button onClick={() => publishNow(publication.id)}>Опубликовать сейчас</button>}{["APPROVED", "SCHEDULED"].includes(publication.status) && <button onClick={() => schedulePublication(publication.id)}>Назначить / перенести</button>}{publication.status === "FAILED" && publication.retry_allowed && <button onClick={() => retryPublication(publication.id)}>Повторить</button>}{!publication.reconciliation_required && !["PUBLISHED", "CANCELLED", "PUBLISHING"].includes(publication.status) && <button className="secondary" onClick={() => cancelPublication(publication.id)}>Отменить</button>}</div> : item.status === "APPROVED" && <button onClick={() => preparePublication(item)}>Подготовить публикацию</button>}</div>; })}
    <div className="page-header"><h2>Календарь публикаций</h2><span>Время показано в часовом поясе браузера</span></div>
    {Object.entries(calendarGroups).map(([date, items]) => <section key={date} aria-label={`Публикации ${date}`}><h3>{date}</h3><ul>{items.map((item) => <li key={item.publication_id}><strong>{item.title}</strong> · {item.channel} · {item.status}{item.scheduled_at ? ` · ${formatDateTime(item.scheduled_at)}` : item.published_at ? ` · опубликовано ${formatDateTime(item.published_at)}` : ""}</li>)}</ul></section>)}
    {upcoming.length ? <ul aria-label="Предстоящие публикации">{upcoming.map((item) => <li key={item.publication_id}><strong>{item.title}</strong> · {item.channel} · {formatDateTime(item.scheduled_at ?? "")} · {item.status}</li>)}</ul> : <p>Запланированных публикаций нет.</p>}
    <h3>Активность</h3>{activities.length ? <ul>{activities.map((event) => <li key={event.id}>{new Date(event.created_at).toLocaleString("ru-RU")} — {event.event_type}</li>)}</ul> : <p>Событий пока нет.</p>}
  </section></main>;
}
